services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHUNK_SIZE=1000
      - BULK_BATCH=1000
      - TOTAL_ORDERS=1000000
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - api
      - redis
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULK_BATCH=500
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
